var express = require('express');
const asyncHandler = require('express-async-handler');
var router = express.Router();
const { ObjectId } = require('bson');
const Salepoint = require('../models/salepoint');
const User = require('../models/user');
const { authenticate } = require('./auth');
const { broadcastMessage } = require('../messaging');

/**
 * @api {post} /salepoints Create a salepoint
 * @apiName CreateSalepoint
 * @apiGroup Salepoint
 * @apiVersion 1.0.0
 * @apiDescription Registers a new salepoint.
 *
 * @apiUse SalepointInRequestBody
 * @apiUse SalepointInResponseBody
 * @apiUse SalepointValidationError
 * @apiSuccess (Response body) {String} id A unique identifier for the salepoint generated by the server
 *
 * @apiExample Example
 *     POST /salepoints HTTP/1.1
 *     Content-Type: application/json
 *
 * {
 *     "address": "ruedespres",
 *     "picture": "/img/ruedespres.jpg"
 *      "paymentMethod": "Card",
 *      "geolocation": {
 *          "location":"Point",
 *          "coordinates": [ -73.856077, 40.848447 ]
 *      },
 *      "userId":"61938a9304230581f9fc2844"
 *
 *  }
 *
 * @apiSuccessExample 201 Created
 *     HTTP/1.1 201 Created
 *     Content-Type: application/json
 *     Location: https://localsearch-ch.herokuapp.com/salepoints/61938a9304230581f9fc2844
 *
 *{
 *   "address": "ruedespres",
 *   "picture": "/img/ruedespres.jpg",
 *   "paymentMethod": "Card",
 *   "geolocation": {
 *       "location": "Point",
 *       "coordinates": [
 *           -73.856077,
 *           40.848447
 *       ]
 *   },
 *   "userId": "61938a9304230581f9fc2844",
 *   "items": [],
 *   "_id": "6193a08355073cd45269ecfa",
 *   "creationDate": "2021-11-16T12:13:55.124Z",
 *   "lastModified": "2021-11-16T12:13:55.124Z",
 *   "__v": 0
 *}
 */
router.post('/', authenticate, asyncHandler(async (req, res, next) => {

  const exists = await User.countDocuments({
    _id: req.body.userId
  });

  if (!exists) {
    return res.status(400).send('User ID missing or invalid')
  }

  const newSalepoint = new Salepoint(req.body);
  await newSalepoint.save();
  res.status(201).send(newSalepoint);
  broadcastMessage({ salepoint: newSalepoint });

}));


/**
 * @api {get} /salepoints List salepoint
 * @apiName RetrieveSalepoint
 * @apiGroup Salepoint
 * @apiVersion 1.0.0
 * @apiDescription Retrieves a paginated list of Salepoint sorted by name (in alphabetical order).
 *
 * @apiUse SalepointInResponseBody
 *
 *
 * @apiExample Example
 *     GET /salepoints?page=1&pageSize=100 HTTP/1.1
 *
 * @apiSuccessExample 200 OK
 *     HTTP/1.1 200 OK
 *     Content-Type: application/json
 *     Link: https://localsearch-ch.herokuapp.com/salepoints?page=1&pageSize=100
 *
 * {
 *  "page": 1,
 *  "pageSize": 100,
 *  "total": 2,
 *  "data": [
 * {
 *    "address": "ruedespres",
 *    "picture": "/img/ruedespres.jpg"
 *    "paymentMethod": "Card",
 *    "geolocation": {
 *        "location": "Point",
 *        "coordinates": [
 *            -73.856077,
 *            40.848447
 *        ]
 *    },
 *    "userId": "61938a9304230581f9fc2844",
 *    "items": [],
 *    "_id": "6193a08355073cd45269ecfa",
 *    "creationDate": "2021-11-16T12:13:55.124Z",
 *    "lastModified": "2021-11-16T12:13:55.124Z",
 *    "__v": 0
 * },
  * {
 *    "address": "Avenue des champs",
 *    "picture": "/img/AvenueDesChamps.jpg"
 *    "paymentMethod": "Twint",
 *    "geolocation": {
 *        "location": "Point",
 *        "coordinates": [
 *            -53.856077,
 *            30.848447
 *        ]
 *    },
 *    "userId": "61938a9304230581f9fc2844",
 *    "items": [],
 *    "_id": "4673a08355073cd45269ebts",
 *    "creationDate": "2021-11-16T12:13:55.124Z",
 *    "lastModified": "2021-11-16T12:13:55.124Z",
 *    "__v": 0
 * }
 *    ]
 * }
 */
router.get('/', asyncHandler(async (req, res, next) => {
  const total = await Salepoint.count();
  let query = querySalepoints(req);

  let page = parseInt(req.query.page, 10);
  if (isNaN(page) || page < 1) {
    page = 1;
  }
  // Parse the "pageSize" param (default to 100 if invalid)
  let pageSize = parseInt(req.query.pageSize, 10);
  if (isNaN(pageSize) || pageSize < 0 || pageSize > 100) {
    pageSize = 100;
  }
  // Apply skip and limit to select the correct page of elements
  query = query.skip((page - 1) * pageSize).limit(pageSize);

  query = await query.exec();

  res.send({
    page: page,
    pageSize: pageSize,
    total: total,
    data: query
  });

}));


/**
 * @api {get} /salepoints/:id GET salepoint by id and associated users & items
 * @apiName RetrieveSalepoint
 * @apiGroup Salepoint
 * @apiVersion 1.0.0
 * @apiDescription Retrieves one Salepoint.
 *
 * @apiUse SalepointIdInUrlPath
 * @apiUse SalepointInResponseBody
 * @apiUse SalepointNotFoundError
 *
 * @apiExample Example
 *     GET /salepoints/6193a08355073cd45269ecfa HTTP/1.1
 *
 * @apiSuccessExample 200 OK
 *     HTTP/1.1 200 OK
 *     Content-Type: application/json
 *
 * {
 *    "address": "ruedespres",
 *    "picture": "/img/ruedespres.jpg"
 *    "paymentMethod": "Card",
 *    "geolocation": {
 *        "location": "Point",
 *        "coordinates": [
 *            -73.856077,
 *            40.848447
 *        ]
 *    },
 *    "userId": "61938a9304230581f9fc2844",
 *    "items": [],
 *    "_id": "6193a08355073cd45269ecfa",
 *    "creationDate": "2021-11-16T12:13:55.124Z",
 *    "lastModified": "2021-11-16T12:13:55.124Z",
 *    "__v": 0
 * }
 */
router.get('/:id', loadSalepointFromParamsMiddleware, async function (req, res, next) {
  res.send(req.salepoint);
});


/**
 * @api {patch} /salepoints/:id Partially update a salepoint
 * @apiName PartiallyUpdateSalepoint
 * @apiGroup Salepoint
 * @apiVersion 1.0.0
 * @apiDescription Partially updates a salepoint's data (only the properties found in the request body will be updated).
 * All properties are optional.
 *
 * @apiUse SalepointIdInUrlPath
 * @apiUse SalepointInRequestBody
 * @apiUse SalepointInResponseBody
 * @apiUse SalepointNotFoundError
 * @apiUse SalepointValidationError
 *
 * @apiExample Example
 *     PATCH /salepoints/6193a08355073cd45269ecfa HTTP/1.1
 *     Content-Type: application/json
 *
 *     {
 *       "address": "Rue des pres 31"
 *     }
 *
 * @apiSuccessExample 200 OK
 *     HTTP/1.1 200 OK
 *     Content-Type: application/json
 *
 * {
 *    "address": "Rue des pres 31",
 *    "picture": "/img/ruedespres.jpg"
 *    "paymentMethod": "Card",
 *    "geolocation": {
 *        "location": "Point",
 *        "coordinates": [
 *            -73.856077,
 *            40.848447
 *        ]
 *    },
 *    "userId": "61938a9304230581f9fc2844",
 *    "items": [],
 *    "_id": "6193a08355073cd45269ecfa",
 *    "creationDate": "2021-11-16T12:13:55.124Z",
 *    "lastModified": "2021-11-16T12:13:55.124Z",
 *    "__v": 0
 * }
 */
router.patch('/:id', authenticate, loadSalepointFromParamsMiddleware, checkOwnerOrAdmin, asyncHandler(async (req, res, next) => {

  if (req.body.address !== undefined) {
    req.salepoint.address = req.body.address;
  }

  if (req.body.paymentMethod !== undefined) {
    req.salepoint.paymentMethod = req.body.paymentMethod;
  }

  if (req.body.picture !== undefined) {
    req.salepoint.picture = req.body.picture;
  }

  await req.salepoint.save();
  res.status(200).send(`Salepoint ${req.salepoint.address} has been succesfully updated!`)

}));

/* DELETE salepoint by id */
/**
 * @api {delete} /salepoints/:id Delete a salepoint
 * @apiName DeleteSalepoint
 * @apiGroup Salepoint
 * @apiVersion 1.0.0
 * @apiDescription Permanently deletes a salepoint
 * 
 * @apiExample Example
 *     DELETE /salepoints/6193a08355073cd45269ecfa HTTP/1.1
 * 
 * @apiSuccessExample 204 No Content
 *     HTTP/1.1 204 No Content
 */
router.delete('/:id', authenticate, loadSalepointFromParamsMiddleware, checkOwnerOrAdmin, asyncHandler(async (req, res, next) => {
  await Salepoint.deleteOne({
    _id: req.params.id
  });

  res.status(200).send(`Ressource : ${req.salepoint.address} deleted`)
}));


function querySalepoints(req) {

  let query = Salepoint.find();

  if (ObjectId.isValid(req.query.userId)) {
    query = query.where('userId').equals(req.query.userId);
  }

  if (req.query.paymentMethod !== undefined) {
    query = query.where('paymentMethod').equals(req.query.paymentMethod);
    console.log(`Filtered using ${req.query.paymentMethod}`)
  }


  if(!isNaN(req.query.lat) && !isNaN(req.query.lon)) {
    console.log('Finding point')
    query.where('location').near({
      center: {
        type: 'Point',
        coordinates: [req.query.lon, req.query.lat]
      },
    })
  }

  return query;
}

async function loadSalepointFromParamsMiddleware(req, res, next) {
  const salepointId = req.params.id;
  if (!ObjectId.isValid(salepointId)) {
    return salepointNotFound(res, salepointId)
  }

  const salepoint = await Salepoint.findById(req.params.id);
  if (!salepoint) {
    return salepointNotFound(res, salepointId)
  }

  req.salepoint = salepoint;
  next();
}

function salepointNotFound(res, salepointId) {
  return res.status(404).type('text').send(`No salepoint found with ID ${salepointId}`)
}

function checkOwnerOrAdmin(req, res, next) {
  const autho = req.currentUserPermissions === 'admin' || req.salepoint.userId.toString() === req.currentUserId;
  console.log(req.currentUserId);
  console.log(req.salepoint.userId);
  if (!autho) {
    return res.status(403).send('Insufficient permissions')
  }
  next();
}

/**
 * @apiDefine SalepointIdInUrlPath
 * @apiParam (URL path parameters) {String} id The unique identifier of the Salepoint to retrieve
 */

/**
 * @apiDefine SalepointInRequestBody
 * @apiParam (Request body) {String{3..300}} address The address of the Salepoint 
 * @apiParam (Request body) {String} picture Picture of the Salepoint
 * @apiParam (Request body) {String="Card", "Cash", "Twint"} paymentMethod Payment method of the salepoint
 * @apiParam (Request body) {object} geolocation The geolocation of the Salepoint
 * @apiParam (Request body) {String="Point"} location the point of the location 
 * @apiParam (Request body) {[Number]} coordinate The coordinate of the salepoint
 * @apiParam (Request body) {Schema.Types.ObjectId} userId The ID of the owner of the Salepoint
 */

/**
 * @apiDefine SalepointInResponseBody
 * @apiSuccess (Response body) {String} id The unique identifier of the Salepoint
 * @apiSuccess (Response body) {String} address The address of the Salepoint 
 * @apiSuccess (Response body) {String} picture Picture of the Salepoint
 * @apiSuccess (Response body) {String} paymentMethod Payment method of the salepoint
 * @apiSuccess (Response body) {object} geolocation The geolocation of the Salepoint
 * @apiSuccess (Response body) {String="Point"} location the point of the location 
 * @apiSuccess (Response body) {[Number]} coordinate The coordinate of the salepoint
 * @apiSuccess (Response body) {Schema.Types.ObjectId} userId The ID of the owner of the Salepoint
 * @apiSuccess (Response body) {[Schema.Types.ObjectId]} items List of items in the Salepoint
 * @apiSuccess (Response body) {Date} creationDate The creation's date of the salepoint
 * @apiSuccess (Response body) {Date} lastModified The date of the last modification of the salepoint 
*/

/**
 * @apiDefine SalepointNotFoundError
 *
 * @apiError {Object} 404/NotFound No Salepoint was found corresponding to the ID in the URL path
 *
 * @apiErrorExample {json} 404 Not Found
 *     HTTP/1.1 404 Not Found
 *     Content-Type: text/plain
 *
 *     No Salepoint found with ID 61938a9304230581f9fc2844
 */

/**
 * @apiDefine SalepointValidationError
 *
 * @apiError {Object} 422/UnprocessableEntity Some of the Salepoint's properties are invalid
 *
 * @apiErrorExample {json} 422 Unprocessable Entity
 *     HTTP/1.1 422 Unprocessable Entity
 *     Content-Type: application/json
 *
 *     {
 *       "message": "Salepoint validation failed",
 *       "errors": {
 *         "paymentMethod": {
 *           "kind": "enum",
 *           "message": "`test` is not a valid enum value for path `paymentMethod`.",
 *           "name": "ValidatorError",
 *           "path": "paymentMethod",
 *           "properties": {
 *             "enumValues": [
 *               "Card",
 *               "Cash",
 *               "Twint"
 *             ],
 *             "message": "`{VALUE}` is not a valid enum value for path `{PATH}`.",
 *             "path": "paymentMethod",
 *             "type": "enum",
 *             "value": "test"
 *           },
 *           "value": "test"
 *         }
 *       }
 *     }
 */

module.exports = router;